module.exports = {
  globalSetup: "jest-preset-angular/global-setup",
  roots: ["<rootDir>", "src/"],
  modulePaths: ["<rootDir>", "src/"],
  moduleFileExtensions: ["ts", "html", "js", "json"],
  collectCoverage: true,
  coverageReporters: ["json", "html", "lcov", "text", "text-summary"],
  preset: "jest-preset-angular",
  setupFilesAfterEnv: ["<rootDir>/setup-jest.ts"],
  collectCoverageFrom: [
    "<rootDir>/src/app/**/*.ts",
    "!<rootDir>/src/app/**/public-api.ts",
    "!<rootDir>/src/app/**/*.module.ts",
    "!<rootDir>/src/app/**/*.directive.ts",
    "!<rootDir>/src/app/**/*.mock.ts",
  ],
  testPathIgnorePatterns: ["<rootDir>/node_modules/", "<rootDir>/package.json"],
  testMatch: ["**/+(*.)+(spec|test).+(ts)?(x)"],
  modulePathIgnorePatterns: ["<rootDir>/dist/"],
};
